version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "uv"
    directory: "/__helpers/CR_simulcast_config_gen"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"