name: Bug
description: File a bug report
title: "[BUG]: "
assignees:
  - HyperNylium
labels:
  - bug
body:
  - type: input
    id: version
    attributes:
      label: Image version
      description: Which version/tag of mdnx-auto-dl are you using?
      placeholder: "1.0.0 or :latest"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details about your issue
      description: Provide any extra details that will help reproduce or understand the bug.
      placeholder: "Steps to reproduce, expected behavior, actual behavior, screenshots..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs from app.log
      description: >
        Please paste the relevant content from `app.log` here.
      render: shell
    validations:
      required: true
