mdnx_cr_monitor_series_id: {}
mdnx_hidive_monitor_series_id: {}
mdnx_adn_monitor_series_id: {}
cdl_cr_monitor_series_id: {}
cdl_hidive_monitor_series_id: {}
cdl_adn_monitor_series_id: {}
cdl_disney_monitor_series_id: {}
cdl_netflix_monitor_series_id: {}
cdl_amazon_monitor_series_id: {}

destinations:
    mdnx-crunchyroll:
        dir: "/data/Anime"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    mdnx-hidive:
        dir: "/data/Anime"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    mdnx-adn:
        dir: "/data/Anime"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    cdl-crunchyroll:
        dir: "/data/Anime"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    cdl-hidive:
        dir: "/data/Anime"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    cdl-adn:
        dir: "/data/Anime"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    cdl-disney:
        dir: "/data/TV Shows"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    cdl-netflix:
        dir: "/data/TV Shows"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"
    cdl-amazon:
        dir: "/data/TV Shows"
        folder_structure: "${seriesTitle}/S${season}/${seriesTitle} - S${seasonPadded}E${episodePadded}"

app:
    MDNX_CR_ENABLED: false
    MDNX_CR_USERNAME: ""
    MDNX_CR_PASSWORD: ""
    MDNX_HIDIVE_ENABLED: false
    MDNX_HIDIVE_USERNAME: ""
    MDNX_HIDIVE_PASSWORD: ""
    MDNX_ADN_ENABLED: false
    MDNX_ADN_USERNAME: ""
    MDNX_ADN_PASSWORD: ""
    BACKUP_DUBS:
        - "zho"
    CHECK_MISSING_DUB_SUB: true
    CHECK_FOR_UPDATES_INTERVAL: 3600
    EPISODE_DL_DELAY: 30
    LOG_LEVEL: "info"

mdnx:
    cli-defaults:
        q: 0
        partsize: 3
        dubLang:
            - "jpn"
            - "eng"
        dlsubs:
            - "en"
        defaultAudio: "jpn"
        defaultSub: "eng"
        vstream: "androidtv"
        astream: "androidtv"
        tsd: false

cardinaldl:
    crunchyroll:
        videoquality: "1080p@@sdr"
        audioquality: "aac@2.0"
        fallback: true
        outputformat: "mkv"
        dublang:
            - "JP"
            - "EN"
        dlsubs:
            - "EN"

    hidive:
        videoquality: "1080p@@sdr"
        audioquality: "aac@2.0"
        fallback: true
        outputformat: "mkv"
        dublang:
            - "JP"
            - "EN"
        dlsubs:
            - "EN"

    adn:
        videoquality: "1080p@@sdr"
        audioquality: "aac@2.0"
        fallback: true
        outputformat: "mkv"
        dublang:
            - "JP"
            - "EN"
        dlsubs:
            - "EN"

    disney:
        videoquality: "1080p@@sdr"
        audioquality: "aac@2.0"
        fallback: true
        outputformat: "mkv"
        dublang:
            - "EN"
        dlsubs:
            - "EN"

    netflix:
        videoquality: "1080p@@sdr"
        audioquality: "aac@2.0"
        fallback: true
        outputformat: "mkv"
        dublang:
            - "EN"
        dlsubs:
            - "EN"

    amazon:
        videoquality: "1080p@@sdr"
        audioquality: "aac@2.0"
        fallback: true
        outputformat: "mkv"
        dublang:
            - "EN"
        dlsubs:
            - "EN"

extra_features:
    trackforge:
        services:
            mdnx-crunchyroll:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            mdnx-hidive:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            mdnx-adn:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            cdl-crunchyroll:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            cdl-hidive:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            cdl-adn:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            cdl-disney:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            cdl-netflix:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""

            cdl-amazon:
                enabled: false
                workers: 1
                muxer: "auto"
                profile: ""
