services:
  app:
    container_name: mdnx-auto-dl
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 6000:6000
    environment:
      # Flask host and port
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=6000

      # template and static folder locations
      - TEMPLATE_FOLDER=appdata/templates
      - STATIC_FOLDER=appdata/static

      # Log settings
      - LOG_LEVEL=DEBUG
      - LOG_FILE=appdata/logs/app.log
