

class DISNEYPLUS_ZLO_API:
    def __init__(self): ...

    def process_console_output(self): ...

    def test(self): ...

    def start_monitor(self): ...

    def stop_monitor(self): ...

    def update_monitor(self): ...

    def cancel_active_download(self): ...

    def _run_download(self): ...

    def download_episode(self): ...
