name: Build & publish Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Optional SemVer to tag the image with (e.g. 0.3.2)."
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # add the user-supplied SemVer **only if** one was provided
            type=raw,value=${{ inputs.version }},enable={{ inputs.version != '' }}
            # always add the moving latest tag
            type=raw,value=latest

      - name: Build & push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show digest
        run: echo "Digest ⇒ ${{ steps.build.outputs.digest }}"
