name: Create base image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/hypernylium/mdnx-auto-dl-base
          tags: |
            type=raw,value=latest

      - name: Build & push base image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
