name: Build active image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. 0.0.1)"
        required: false
        default: ""

permissions:
  contents: read
  packages: write

jobs:
  build-active-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            ${{ inputs.version != '' && format('type=raw,value={0}', inputs.version) || '' }}

      - name: Build & push image (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
