name: Build & push active image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. 0.0.1)."
        required: false
        default: ""

permissions:
  contents: read
  packages: write

jobs:
  build-active-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            ${{ inputs.version != '' && format('type=raw,value={0}', inputs.version) || '' }}

      - name: Pull base image
        run: docker pull ghcr.io/hypernylium/mdnx-auto-dl-base:latest || true

      - name: Build & push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
